$(document).ready(function(){
    $('#xemnhieu').click(function(){
        $('#menu1').css({'display':'none'});
        $('#menu2').css({'display':'block'});
    });
    $('#moinhat').click(function(){
        $('#menu1').css({'display':'block'});
        $('#menu2').css({'display':'none'});
    });
});
